### ISSUE TITLE
The device or user is not allowed to make the purchase

### ISSUE THREAD

**Issue by marshallcool** [RevenueCat/react-native-purchases#113]
help with configuring react-native SDK on android, when trying to call restoreTransactions or getOfferings method, I get errors:

Starting connection for com.android.billingclient.api
 W/Finsky: [205] fzj.a(400): Billing unavailable for this package and user.

1) ERROR: The device or user is not allowed to make the purchase. | Billing is not available in this device. DebugMessage: Google Play In-app Billing API version is less than 3. ErrorCode: BILLING_UNAVAILABLE

2) In-app billing API version 3 is not supported on this device.
help understand which side of the problem

**Comment by vegaro** [comment]
Are you using an emulator? If so does it have play services? Are you logged in in the play store? What version of Android are you using?

**Comment by marshallcool** [comment]
1) i use real device
2) yes
3) yes
4) android version - 5.0, Sony E2312

**Comment by vegaro** [comment]
This error means the IAB v3 is not installed on the device. This could be caused by:

- An old version of the play services
- Play services not existing in the device
- Another Play Services error (maybe cleaning caches 
- Maybe a rooted device with modified play services?
- User is not logged in in the Play Store
- More info https://stackoverflow.com/a/21275043/1148405

This is related to Google Play Services and not RevenueCat.
