### ISSUE TITLE
Create unified error enums or types

### ISSUE THREAD

**Issue by rkotzy** [RevenueCat/react-native-purchases#127]
Similar to the closed Flutter issue: https://github.com/RevenueCat/purchases-flutter/issues/3

Expose error codes as enums or equivalent so they don't have to be hard-coded.

**Comment by aleqsio** [comment]
Extending on this issue, found this to be the most confusing aspect of adding RevenueCat to a react native app. I'd expect enums provided here https://docs.revenuecat.com/docs/errors to be available as fields on errors thrown from this sdk, but this is not the case.
There are a lot of different enum values for same errors like PurchaseCancelledError, PURCHASE_CANCELLED and USER_CANCELLED (guessing the last one is coming from google play).
Additionally, can't seem to find an explanation to the numeric error codes (it's not the order on that page)

**Comment by tomwanzek** [comment]
Just so this issue is not considered stale, not only is it still relevant, it is exacerbated by the fact that the `userCancelled: boolean` flag is not exposed on the TypeScript definitions of `PurchasesError`, which makes it had to catch and differentially handle this "normal course of actions error".

See #228

**Comment by aboedo** [comment]
Closing this issue as it's been fixed in release 4.1.2 🎉
