### ISSUE TITLE
Can this be used with React Native Web?

### ISSUE THREAD

**Issue by haveamission** [RevenueCat/react-native-purchases#143]
I am looking for a subscription library that works with React Native Web.

Unfortunately, there's really little in the way of libraries for this particular platform - just basic React Native (iOS/Android).

Preferably I'd like all three, in order to reduce the amount of code that needs to be written

**Comment by aboedo** [comment]
Hi! 👋 Sorry for the late reply. Our React Native SDK uses Google Play Billing on Android and StoreKit on iOS under the hood. 
For web purchases, on the other hand, you can use our REST API (https://docs.revenuecat.com/reference). 
If using the REST API directly from the React Native Web app gives you Cross-Origin errors, you may have to call this API from your own backend though (a Firebase Function for example), and send/get the data from RevenueCat from there to be consumed. 

Closing this issue for now, because we reserve GitHub issues for bug reports, but feel free to follow up with RevenueCat Support (https://support.revenuecat.com/) if you need more assistance or have more questions around web purchases.

**Comment by haveamission** [comment]
@aboedo How is the best way to get my Stripe plans for use here, as they're needed to subscribe a user?

**Comment by aboedo** [comment]
@haveamission I think the best path is probably to go through our support at https://support.revenuecat.com/, since they'll be better equipped to help your particular case. 

Like I mentioned before, while you can use the REST API directly, you may run into Cross-Origin errors, so there's a chance that you'd have to relay messages back and forth through your own server. But again, our support team would be able to assist in more detail

**Comment by vbylen** [comment]
Would be nice if react-native-web was supported so we could have a unified API for iOS, android and Web at least.

**Comment by ericpoulinnz** [comment]
@aboedo 4 years later, do you know if this is planned by the RC team? React Native is increasingly used as a universal solution, and having a unified purchases SDK would really simplify development.
