### ISSUE TITLE
getOfferings() fails only in iPad Simulators

### ISSUE THREAD

**Issue by aplattinum** [RevenueCat/react-native-purchases#153]
"react-native": "0.62.2",
    "react-native-purchases": "^3.2.0",

Very strange behavior.  I have never had any issues with retrieving the Purchases SDK data until trying it out on the iPad simulators.  Android and all other iPhone simulators and devices have worked perfectly until now.

I am doing the following: 
 
```javascript 
const getOfferings = async () => {
    try {
      let packages = await Purchases.getOfferings();
      let purchasePkg = packages.all.pro_plan.availablePackages;
      setOfferings(purchasePkg);
      console.log(packages);
    } catch {
      console.log('Couldnt get offerings');
    }
  };
```

The call always is rejected but only on iPad.  Any ideas what I should do?

**Comment by mshmoustafa** [comment]
Hey!

StoreKit's stability in the simulator has been historically flaky, resulting in random bugs when fetching products, which is why we recommend testing on a physical device. Let us know if you see any of these same issues on a physical device. I'll close for now since it does sound like your app works, just not in the simulator.
