### ISSUE TITLE
can I use Purchases.identify to get subscription status ?

### ISSUE THREAD

**Issue by GabrielLiade** [RevenueCat/react-native-purchases#223]
Hi everyone,
I use identify to associated my user app id to the revenue cat id 

my question is in order to check the subscription status do I need to use this method : 

`const purchaserInfo = await Purchases.identify(user.id))`

or this method : 

`const purchaserInfo = await Purchases.getPurchaserInfo()`

both are working so I don't know what is the best practice 

thanks

**Comment by aboedo** [comment]
Hi! 

They will both return the `purchaserInfo`, however, `identify` is meant exclusively so that you can tie your user id with a known user in RevenueCat. 
So you'd typically use `getPurchaserInfo` for getting the subscription status whenever you need it, and `identify` specifically for something like when a user logs in. 

Hope that helps, but I'd highly recommend digging deeper into both of these concepts here: [PurchaserInfo](https://docs.revenuecat.com/docs/purchaserinfo) and [Identity](https://docs.revenuecat.com/docs/user-ids)

We reserve GitHub Issues for bug reports, so I'm closing this issue. If you need further assistance getting set up, I'd recommend heading over to our [Help Center](https://support.revenuecat.com/hc/en-us).

**Comment by GabrielLiade** [comment]
Thanks Aboedo
