### ISSUE TITLE
App crash in iPad - [__NSPlaceholderDictionary initWithObjects:forKeys:count:]: - React-Native

### ISSUE THREAD

**Issue by KPUbhada** [RevenueCat/react-native-purchases#224]
Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[5]

**Reported crash in iPad 3rd Generation**

RCPurchaserInfo+HybridAdditions.m - Line 39
-[RCPurchaserInfo(HybridAdditions) dictionary] + 39

RNPurchases.m - Line 325
-[RNPurchases purchases:didReceiveUpdatedPurchaserInfo:] + 325

**Comment by KPUbhada** [comment]
Issue reported in Firebase in iPad.

When popup present for purchase then app crashed as showing in log.
**App crash in RCPurchaserInfo+HybridAdditions.m - Line 39 file in iOS**
![Screenshot 2021-03-29 at 12 31 32 PM](https://user-images.githubusercontent.com/53697474/112798671-e104b200-908a-11eb-9616-363c5b2578b2.png)


Thanks

**Comment by aboedo** [comment]
hi! thanks for reporting. Which version of the `react-native-purchases` plugin are you using?

**Comment by KPUbhada** [comment]
Hi @aboedo 
I have facing issue in "react-native-purchases": "^4.1.0" version. 2 User facing issue with 7 crashes.

Thanks

**Comment by aboedo** [comment]
Thanks!

That means that the crash must be in this line https://github.com/RevenueCat/purchases-hybrid-common/blob/develop/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCPurchaserInfo+HybridAdditions.m#L45, since that's the element at index 5 that's being added to the `dictionary` in that file. 


Since that line is: 

```objective-c
        @"firstSeen": self.firstSeen.formattedAsISO8601,
```

that means that either `firstSeen` or `formattedAsISO8601` is returning `nil`. 
I'm digging in further to understand how that could happen.

**Comment by aboedo** [comment]
@KPUbhada are you still seeing instances of this in the wild? If so, would you mind sharing an appUserID with us in order to debug further? 
We can continue over ZenDesk at https://support.revenuecat.com if it involves sensitive data

**Comment by aboedo** [comment]
@KPUbhada I'm closing out this issue due to inactivity. We issued a backend-side fix in April, which might have fixed the issue, but let us know if you're still seeing instances of this in the wild.
