### ISSUE TITLE
xCode build PurchasesCoreSwift not found

### ISSUE THREAD

**Issue by sandrina-p** [RevenueCat/react-native-purchases#246]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**

I'm using Expo bare and updated from [SDK 40 to SDK 41](https://blog.expo.io/expo-sdk-41-12cc5232f2ef).

Locally, running `npm run ios`, the app starts fine and the purchases works fine. (purchase and restore was what I tried)

However, when I try to create xCode build, it doesn't work. I followed the [React Guide](https://reactnative.dev/docs/next/publishing-to-app-store) as usual, it's on the last step that it fails.

It seems PurchasesCoreSwift no found.

> fatal error: module map file '/Users/sandrina-p/Library/Developer/Xcode/DerivedData/PapersTheGame-aecprcpfcgsomheuxkcfpejjtyib/Build/Intermediates.noindex/ArchiveIntermediates/PapersTheGame/BuildProductsPath/Release-iphoneos/PurchasesCoreSwift/PurchasesCoreSwift.modulemap' not found

I already tried to reinstall the pods (including delete pod lock and folder and cache), but the error keeps happening.

1. Environment
   1. Platform: MacOS
   2. SDK version: 1.10.1
   3. OS version: Catalina 10.15.7
   4. XCode/Android Studio version: 12.3
   5. React Native version: 0.63.4
   6. SDK installation (CocoaPods + version or manual): 1.10.1

**Comment by sandrina-p** [comment]
Hum, I did try my best to follow the template. I was not sure how to add more debug logs :/

**Comment by aboedo** [comment]
@sandrina-p hi! sorry for the delayed response. 
Don't mind the bot, it's still learning 🤖 

We have a new [SDK Troubleshooting Guide](https://docs.revenuecat.com/docs/troubleshooting-the-sdks#issues-when-compiling-or-archiving) which may help, although it seems like you've been pretty thorough. Perhaps `pod deintegrate` would help? 

If the issue is specific to when archiving in Xcode, perhaps there's something problematic in the `Podfile`? Have you tried setting `use_frameworks!` or `use_modular_headers!`?

**Comment by sandrina-p** [comment]
@aboedo, thanks for the reply.

So I did `pod deintegrate` and then `pod install`. The installation went well. Run again the build and got the same error :/

How do I set those things in `Podfile`? Forgive me, I've very newbie when it comes to xcode stuff, I come from JS world.

I added this, saved the file, restarted Xcode, and started the build again. Exact same error.

```diff
target 'PapersTheGame' do
  use_unimodules!
+  use_frameworks!
 + use_modular_headers!
  config = use_native_modules!
```

Btw, the project I'm starting to build is open source, it's a small mobile game  [The Papers Game](https://github.com/sandrina-p/papers-game), in case you want to take a look (I did not commit this last change)

**Comment by aboedo** [comment]
@sandrina-p 🤔 I'm not sure what's going on in that case. I'm a newbie to the Expo world 🤷 

> Btw, the project I'm trying to to build is open source, it's a small mobile game The Papers Game, in case you want to take a look.

Awesome! I ❤️ OSS projects! I'll check it out and see if I can get it to work, and share what I find. Also, 

> Papers is the perfect game for your dinner party. 

This sounds super promising 😃

**Comment by sandrina-p** [comment]
@aboedo , good news, I found something odd. in xcode configs, in general I had "ios 9.0", but Expo 41 requires IOS 11. I changed it to 11.0 and it built correctly! The build worked but the app isn't starting properly. (no errors). I'm debugging and keep you updated.

> This sounds super promising 😃

Thanks, it has been a 1 year project on my free time, it's 80-90% done, almost done! It's just missing the last tricky parts related with releases and polishing

**Comment by sandrina-p** [comment]
Okay, so, I'm closing this issue because it's fixed. I'm still having problems, but it's unrelated.

The problem was the ios version mismatch. Both on podfile and code it must be equal. in my case `11.0`

Podfile:
```
platform :ios, '11.0'
```

![image](https://user-images.githubusercontent.com/14869087/119730991-4cda7f80-be6e-11eb-8112-947ca7e64d7f.png)

**Comment by aboedo** [comment]
@sandrina-p thanks for the update!! I'm glad it's working now. I'll add a note about deployment targets in the Expo-specific docs and in the troubleshooting guide. 
And good luck with The Papers Game! Let us know if you run into any more issues.

**Comment by sandrina-p** [comment]
@aboedo, forgive me, I spoke too soon. I was able to build the project, but `archive` does not work yet. I got this error:

![image](https://user-images.githubusercontent.com/14869087/119733898-11da4b00-be72-11eb-9527-bd02a0b91f05.png)


What am I missing? 🤔

**Comment by aboedo** [comment]
@sandrina-p I've seen quite a few things cause that exact same error log, so it might be anything from headers search paths issues, to using swift < 5, to deployment target (which you've already fixed), dynamic vs frameworks in cocoapods under some set ups, etc. 

do you have a WIP branch that I could check out and try to reproduce?

**Comment by remotecom** [comment]
@aboedo, I see... it seems tricky. You can check [The Papers Game - master](https://github.com/sandrina-p/papers-game) directly :)

**Comment by aboedo** [comment]
@sandrina-p I just checked out the game and was able to archive successfully: 

What I did:
- checked out master
- yarn
- updated deployment target in the project and in the target to 11.0
- replace podfile line for Purchases with `pod 'RNPurchases', :path => '../node_modules/react-native-purchases'` (i.e.: removing the other modifiers)
- commented out `use_frameworks!` and `use_modular_headers!`
- cd ios && pod install
- archive (had to update bundle id and dev team to be able to create an archive, but that shouldn't affect the actual build)
-

**Comment by sandrina-p** [comment]
@aboedo those are good news! I'll try this on the weekend and the  get back to you! Thank u again 😊

**Comment by sandrina-p** [comment]
> updated deployment target in the project and in the target to 11.0

@aboedo, where exactly did u do this? I did in `platform :ios, '11.0'` and in xcode General > Deployment info. Did I miss any other place?

**Comment by aboedo** [comment]
I updated it in the project's settings as well. I'm not sure it actually makes a difference, though. 
<img width="525" alt="Screen Shot 2021-05-30 at 2 42 33 PM" src="https://user-images.githubusercontent.com/3922667/120114380-5b1de980-c155-11eb-8309-1df98f47cdd2.png">

>  To note that the npm version I use is 12.18.2, is the same for you?

I installed `npm @12.18.2`, otherwise I'd get errors when installing dependencies

**Comment by sandrina-p** [comment]
@aboedo, what's you Xcode version? Mine is 12.3. Perhaps there's some extension missing or... 🤔 What about build rules? Anything else that I could provide you in order to help me debug this ?

**Comment by aboedo** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/3922667/120860846-b1779780-c55c-11eb-95a0-c322cc6538cc.png">
 I can give it another shot with Xcode 12.3 next week

**Comment by sandrina-p** [comment]
I don't have BigSur, I'm still on Catallina. I'll update to 12.4 and let you know if it worked

**Comment by rborn** [comment]
We are in the same situation on an Xcode 12.4 (Catalina)

**Comment by aboedo** [comment]
@sandrina-p did you manage to figure this out? 
@rborn have you tried the steps in our [SDK Troubleshooting guide](https://docs.revenuecat.com/docs/troubleshooting-the-sdks#issues-when-compiling-or-archiving)? Those should help with most cases

**Comment by rborn** [comment]
@aboedo the native side of the code is not touched in weeks, last week worked fine (we deployed)

**Comment by aboedo** [comment]
@rborn yeah, the issue is most likely not coming from the native side of the code, but sometimes there are some issues with caching, derived data (especially when switching Xcode versions), differing react-native versions, and even CocoaPods. 

So the steps in the troubleshooting guide mostly help with navigating those kind of issues. They can be really frustrating and hard to debug

**Comment by rborn** [comment]
@aboedo not sure if related but I don't seem to be able to build for release anymore even on my machine, the react-native-xcode.sh fails now. Trying to find out why :|

**Comment by aboedo** [comment]
probably related, yes. But the exact cause is hard to pin down for these things: caching, project configuration, react-native updates, derived data, etc. I definitely encourage you to give [the troubleshooting steps a shot]([SDK Troubleshooting guide](https://docs.revenuecat.com/docs/troubleshooting-the-sdks#issues-when-compiling-or-archiving)) just in case they solve the issues. 
Also, you should try to double-check what react-native version you were using when things were working and see if that's changed, I've had situations where a new react-native release breaks my builds in the past

**Comment by rborn** [comment]
Yeah, looked at that of course, will update if I find anything, thanks for replying 🥰

**Comment by sandrina-p** [comment]
@aboedo forgive me for my late response. I uninstalled xcode and didn't had the opportunity to update to the latest version in Catalina. 
I'll try it again this weekend and let you know. Is there any additional logs I should share in case it fails?

**Comment by rborn** [comment]
@aboedo you were right, it was a nasty error, we changed a name of a file to lowercase and git didn't see this but for some reason it was crashing only when archiving and initially the error was somehow saying that purchase swift modules are not found (we probably forgot to run yarn)
Sorry for hijacking the thread

       	
Daniel Tamas
+34 644 374 865
www.letsemjoy.com

**Comment by aboedo** [comment]
@rborn I'm glad it worked! I'm sorry you ran into that experience. These issues are suuuper hard to find and fix. I'm still looking for solutions that are more foolproof, but for now the troubleshooting guide is the best I could come up with. 

@sandrina-p 🤔 well, if you run into the issue again, then I think the most helpful things would be the versions of everything (i.e.: npm, xcode, react-native, cocoapods, etc), and if you make any changes to the actual code, the branch. 
Essentially anything I can use to try to reproduce, since it had worked correctly for me after the small changes I mentioned.
I hope it starts working, though! 🤞

**Comment by sandrina-p** [comment]
@aboedo, I just uninstall xcode 12.3 and installed 12.4. Now, the build isn't working either. I [recorded a Loom](https://www.loom.com/share/d10a9db6de6f45fd9963b6cd00fe31e8) of me showing the install+run process. Perhaps it gives you any idea of what I might be missing

**Comment by aboedo** [comment]
@sandrina-p for the empty swift file, aside from creating the file, you need to make sure that it's actually added to the Xcode project. This is done by selecting the file in xcode, then on the sidebar to the right, select the File Inspector tab, go to the Target Membership section and checking that the checkbox for your app is selected for that new Swift file.  
I think this isn't the issue in your particular case, because I just tried a fresh clone again and followed the steps I mentioned here https://github.com/RevenueCat/react-native-purchases/issues/246#issuecomment-849904390 and was able to archive again. 
I'm watching the video to try to figure out what might be going on and why the difference in results, I'll report back in a bit.

**Comment by aboedo** [comment]
@sandrina-p found it!! The video was super helpful, thanks! 
you followed the steps perfectly 👌 but you're opening the `.xcproject` file, and you need to open the `.xcworkspace` file instead. 

This is because CocoaPods creates an `.xcworkspace` for your app, which is essentially a grouping of projects, and uses that [to set up and compile the dependencies](https://guides.cocoapods.org/using/using-cocoapods.html#what-is-happening-behind-the-scenes). 

So you had literally everything correct, you just need to close the `.xcproject` in Xcode, then open up the `.xcworkspace` instead

<img width="729" alt="image" src="https://user-images.githubusercontent.com/3922667/123658008-b3edaa00-d807-11eb-920e-cb279c5696fc.png">

Then just run like you were doing before!

**Comment by sandrina-p** [comment]
@aboedo, that was it, the build worked!! 🙌 I don't know how I missed that part (that's how newbie I am with xcode).

Thank you a lot for your patience.

So a TLDR of my solution:
- Ensure version are a match at both xcode settings and podfile (in my case `11.0`)
- Update xcode to 12.4

I'm closing this now :)

**Comment by aboedo** [comment]
@sandrina-p I'm glad it worked!! Let us know if you run into any more issues. Have a great day!
