### ISSUE TITLE
"Native module cannot be null" thrown when importing Purchases in javascript

### ISSUE THREAD

**Issue by samstorino** [RevenueCat/react-native-purchases#247]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
I'm experiencing the same issue outlined by [this closed ticket](https://github.com/RevenueCat/react-native-purchases/issues/23).

I followed the iOS [installation instructions](https://docs.revenuecat.com/docs/reactnative) with auto linking. I then added `import Purchases from 'react-native-purchases';` to one of my files and implemented the purchase logic. Now when I run `expo start` and open the app on either a simulator or physical device (both iOS) I see the below error.

![image](https://user-images.githubusercontent.com/3956864/119285223-6c677300-bbf6-11eb-92dd-30e64a8f3a7e.png)

When I remove the import statement the app loads perfectly fine. Additionally, the app loads fine if I open the associated iOS workspace in Xcode and run from there.

To summarize: importing the `react-native-purchases` dependency anywhere in my app causes `expo` tooling to no longer work.

1. Environment
   1. Platform: macOS
   2. SDK version: 4.1.2 (note: I originally had 3.4.3 which experienced same issues. Upgrading didn't help).
   3. OS version: 10.15.7 (Catalina)
   4. XCode/Android Studio version: 12.3
   5. React Native version: 0.63.4
   6. SDK installation (CocoaPods + version or manual): CocoaPods/auto-install [as outlined here](https://docs.revenuecat.com/docs/reactnative).
   7. How widespread is the issue. Percentage of devices affected: any simulator/device running expo.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue.
See screenshot above.

3. Steps to reproduce, with a description of expected vs. actual behavior
Given an environment that matches mine, install react-native-purchases, then use `expo start` to open the app on an emulator. Expected: app loads without issue. Actual: app shows error (see above image).

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
Related issue: https://github.com/RevenueCat/react-native-purchases/issues/23

**Additional context**
**Expo version:** 40.0.0
**Expo Workflow Type:** bare

Here's a list of my `package.json` dependencies:

```
"dependencies": {
    "@expo-google-fonts/roboto": "^0.1.0",
    "@expo/vector-icons": "^12.0.0",
    "@react-native-async-storage/async-storage": "^1.13.4",
    "@react-native-community/datetimepicker": "^3.0.9",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "@sentry/react-native": "^2.0.2",
    "buffer": "^6.0.3",
    "date-fns": "^2.16.1",
    "expo": "^40.0.0",
    "expo-asset": "~8.2.1",
    "expo-constants": "~9.3.3",
    "expo-file-system": "~9.3.0",
    "expo-font": "~8.4.0",
    "expo-haptics": "~8.4.0",
    "expo-image-manipulator": "~8.4.0",
    "expo-image-picker": "~9.2.0",
    "expo-in-app-purchases": "~9.1.0",
    "expo-linking": "~2.0.1",
    "expo-notifications": "~0.8.2",
    "expo-permissions": "~10.0.0",
    "expo-secure-store": "~9.3.0",
    "expo-splash-screen": "~0.8.1",
    "expo-status-bar": "~1.0.3",
    "expo-updates": "~0.4.1",
    "expo-web-browser": "~8.6.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "0.63.4",
    "react-native-animatable": "^1.3.3",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-appearance": "~0.3.3",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-purchases": "^4.1.2",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.2",
    "react-native-unimodules": "~0.12.0",
    "react-native-web": "~0.13.12",
    "sentry-expo": "^3.0.4"
  },
```

Here's a screenshot of my project's "Frameworks, Libraries, and Embedded Content" section in Xcode. Note that under `Frameworks` I have multiple red files relate to Purchases. I manually added the `libRNPurchases.a` file to "Frameworks, Libraries, and Embedded Content" as a test, but the problem persists. I have since removed the manual addition but the missing file references remained.

![image](https://user-images.githubusercontent.com/3956864/119286062-607cb080-bbf8-11eb-95b9-9a50f347ee85.png)

According to the [installation instructions](https://docs.revenuecat.com/docs/reactnative) it's recommended we use at least React Native 0.64 or greater. Expo doesn't support 0.64 yet, so I can't test whether or not 0.64 would simply resolve this issue.

**Comment by aboedo** [comment]
hi @samstorino! Thanks for opening and sorry for the delay in replying!

`react-native-purchases` currently doesn't work in the managed workflow for Expo, due to some limitations on Expo's side: 

- https://docs.expo.io/introduction/why-not-expo/
- https://expo.canny.io/feature-requests/p/in-app-purchases

It does work on the bare workflow, though, so if you want to do in-app purchases in your Expo app, you'll have to [eject to bare workflow](https://docs.expo.io/workflow/customizing/). 

We'll improve our docs to make this more clear. 

Other notes: 
- When [installing the SDK using auto-linking](https://docs.revenuecat.com/docs/reactnative#option-1-using-auto-linking), there's no need to do the other steps to manually add the framework to the project - Cocoapods takes care of that automatically, and adding it manually would create a duplicate reference, which could lead to unexpected behavior. 

I'm tentatively closing this ticket since this is expected behavior, related to configuration. However, feel free to reply here or open up a new ticket if you run into any bugs. 

We reserve GitHub issues for bug-reports only. If you need more assistance getting set up, please open up a support ticket at https://support.revenuecat.com/, since our support team will be better equipped to help you.

**Comment by samstorino** [comment]
Hi @aboedo , thanks for the reply! I'm using the bare workflow (please see the Additional Context section of my original post). `react-native-purchases` does work in my app, that's not the problem. As mentioned above I'm able to run the app through Xcode, but I can't run it through Expo. When starting the app with `expo start` I receive the aforementioned error screen. Commenting out the import statement for `react-native-purchases` makes this error go away.

Please have another read through my original post when you get a moment, there's more detail there that should help clarify. Can we please reopen this ticket?

**Comment by aboedo** [comment]
@samstorino I'm sorry, I misunderstood the original ticket. 

However, for running with Expo Go, I think you'll still [have to add extra guards](https://docs.expo.io/bare/exploring-bare-workflow/#open-the-project-with-the-expo-go) to make sure that you're not calling stuff that it's included in the Expo SDK. 
From the error message `"Native module cannot be null"` and the line _"after you’ve added native code that the client doesn’t support"_ in the link I just posted, I think this may be the issue. 

One way around this would be to use `npx react-native run-ios` instead of `expo start`. Would that work for you?

**Comment by samstorino** [comment]
No worries @aboedo , thanks for the quick follow-up! Yes, `npx react-native run-ios` will work, I just wanted to bottom out on why I was experiencing issues using Expo. This makes sense now - I'll operate under the assumption that `react-native-purchases` simply isn't natively supported by Expo Go, and will need to be conditionally guarded against.

Thanks again for the help!
