### ISSUE TITLE
Offers are not shown in emulator and tests.

### ISSUE THREAD

**Issue by mikipdia** [RevenueCat/react-native-purchases#289]
The component is configured together with RenueveCat, and storekit is used to see the test offers, my question is that if to see the production options it is necessary to release the app to be approved with the stores, why are the production offers not they are visible in preubas and emulator or if in your case it is only necessary to test on a physical device.

const offerings = await Purchases.getOfferings ();
This is the option that is not returning the offers in production, it is in IOS and Android.

**Comment by vegaro** [comment]
In the case of Android, the app has to be released to a closed track in order to see the offerings. After the first release to the closed track, your app will be able to load the products while testing from Android Studio (no need to re release to a closed track every time you make a change). More info on that [here](https://docs.revenuecat.com/docs/google-play-store#create-a-closed-track-and-add-a-tester-to-it)

Regarding iOS, make sure your products are Ready to Submit. We have this old blogpost https://www.revenuecat.com/blog/app-store-connect-in-app-purchase-guide that explains the most common problems when setting up your products. Apart from that, our [documentation](https://docs.revenuecat.com/docs/apple-app-store) has more details about the difference between simulators and physical devices.

**Comment by mikipdia** [comment]
In iOS only those that are ready to send appear? In this case I am trying to show two products that are already approved. To test in production, would it have to be with products that are only ready to ship?

**Comment by mikipdia** [comment]
To make real purchases and to take the products into production, do you have to launch the app? or how is the sandbox disabled?

**Comment by mikipdia** [comment]
.

**Comment by vegaro** [comment]
The sandbox is disabled when launching the app downloaded from the App Store. That's what's considered production. You would have to go through App Review and get your app approved in order to be able to download it from the App Store. You won't be able to go through app review if the products are not loading correctly, so make sure those load properly in sandbox.

In order to better assist you with your questions, do you mind using our online community (https://community.revenuecat.com). It's easier to get more help for this type of questions in our community rather than in GitHub. We use GitHub for bugs and not for RevenueCat/configuration support. We have a whole team monitoring that community and you can also get support from other users 😺 

I am going to be closing this issue since I think it's more suited as a question in the community.
