### ISSUE TITLE
Error when setting attribute with key "activeFor" on iOS

### ISSUE THREAD

**Issue by beetlebum** [RevenueCat/react-native-purchases#330]
A very odd issue I've come across recently using version `4.5.1`.
If I try to set a user attribute with the key `activeFor`, I get the following error:

![image](https://user-images.githubusercontent.com/227258/153203625-574ac6e3-ffe2-4269-8bac-cf4c01fc131c.png)

A simplified version of the code would be:

```
    await Purchases.setAttributes({ activeFor: '10' });
```

- Changing the value associated to the key makes no difference.
- Setting a different key like `activeFor1` works.

I haven't found any reference within the code or the documentation to this being a reserved keyword. It looks like  the value is being treated differently when associated with that key.

**Comment by beetlebum** [comment]
@joshdholtz thanks, that makes total sense. Is it possible to clear the cache with the sdk?

**Comment by joshdholtz** [comment]
@beetlebum I don't think we have a Public API to clear the cache in the SDK 😔 

**Option 1:** Uninstall the app. The cache doesn't persist between installs.
**Option 2:** If you background the app and open it back up, the app syncs up to the API. It seems like sending up an integer `10` to the API works (🤷‍♂️) and that will clear the cache. I was having a hard time producing this because of this reason.

**Option 1** is probably the best if you are just developing locally 😊 

Let me know if either of those work for you!

**Comment by beetlebum** [comment]
@joshdholtz it's fine, the code was never released to production, just wondering if there was a workaround in case it happened again in the future.
Thanks for your help, really appreciate it.

**Comment by joshdholtz** [comment]
@beetlebum Glad that worked! And this issue will actually be fixed when we migrate React Native from our iOS v3 to v4 so nobody should run into the issue again after that 😇 

Hit us up if you ever have any other issues or questions!
