### ISSUE TITLE
Apple reject app due to RCPurchaseErrorDomain.

### ISSUE THREAD

**Issue by KPUbhada** [RevenueCat/react-native-purchases#337]
- I have updated Purchases SDK to the latest version
- I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- I have searched the [Community](https://community.revenuecat.com)
- I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
In real device and while testing I have not get any issue. I have setup react-native-purchases package for long time but recent version is rejected due to **error code - 9**, **error domain - RCPurchasesErrorDomain**. I have not idea about this error. Please help me how can we resolved this.

1. Environment
   1. Platform: Mac
   2. SDK version: 4.5.2
   3. OS version: 11.3
   4. Xcode/Android Studio version: 13.2.1
   5. React Native version: 0.65
   6. SDK installation (CocoaPods + version or manual):
   7. How widespread is the issue. Percentage of devices affected.

Thanks
Ketan

**Comment by codykerns** [comment]
Hey @KPUbhada! To confirm, you're able to test correctly on-device, but when submitting for review you get a rejection? Because of Apple's flaky sandbox environment, we often receive reports of inexplicable rejections. It's typically a problem with their own environment, but you'll have to resubmit (some developers have had to submit the same build up to a dozen times before being approved). 

This particular issue (RCPurchasesErrorDomain 9) is a missing receipt file. I would expect it to resolve with a different reviewer on a subsequent review.

**Comment by KPUbhada** [comment]
Hi @codykerns I have resubmit app 3 times. But every time I have get same issue with same reason (RCPurchasesErrorDomain 9). I need to clear how can we resolved this.

**Comment by KPUbhada** [comment]
Here is rejection reason by apple

We continue to find that your in-app purchase products exhibited one or more bugs when reviewed on iPad running iOS 15.4 on Wi-Fi.

- The app kept displaying the following error, when we tapped on “Start rewiring”:
“Something went wrong: 9 - RCPurchasesErrorDomain”.

Next Steps

When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment. The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code "Sandbox receipt used in production," you should validate against the test environment instead.


**@codykerns As about all replay by apple. So they provide some suggestion to fixed this issue. We need to use sandbox receipt for sandbox. So any addiction code need to with implement with this suggestion in react-native-purchase repo?**

**Comment by djendacott** [comment]
Hi @codykerns, I work with @KPUbhada and just thought I'd weigh in on this issue we're (still) experiencing.

There seems to be a hypothesis at RevenueCat that this is a flaw to with a flaky test environment at Apple. How sure are we of this?

I ask because for 8 years (6 years react-native purchases, almost 2 years RevenueCat) we have never once had a purchase related issue, only to be rejected by **both** Apple and Google a day apart with the same issue.

As @KPUbhada just mentioned, we've now submitted to Apple three times, and requested review with multiple new test accounts, and on multiple devices.

Btw this happened immediately after updating to RN 0.65. Is there some SDK issue potentially at play?

**Comment by KPUbhada** [comment]
Here is the rejection reason provided by Apple.
We continue to find that your in-app purchase products exhibited one or more bugs when reviewed on iPad running iOS 15.4 on Wi-Fi.
The app kept displaying the following error, when we tapped on “Start rewiring”:
“Something went wrong: 9 - RCPurchasesErrorDomain”.
Next Steps
When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment.
The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code “Sandbox receipt used in production,” you should validate against the test environment instead.
[@codykerns](https://github.com/codykerns) Local sandbox testing is working perfectly, as is TestFlight testing. Is there anything else we could be overlooking?

**Comment by KPUbhada** [comment]
Here is the rejection reason provided by Apple.
We continue to find that your in-app purchase products exhibited one or more bugs when reviewed on iPad running iOS 15.4 on Wi-Fi.
The app kept displaying the following error, when we tapped on “Start rewiring”:
“Something went wrong: 9 - RCPurchasesErrorDomain”.
Next Steps
When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment.
The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code “Sandbox receipt used in production,” you should validate against the test environment instead.
[@codykerns](https://github.com/codykerns) Local sandbox testing is working perfectly, as is TestFlight testing. Is there anything else we could be overlooking?

**Comment by codykerns** [comment]
Hey @djendacott and @KPUbhada,

> There seems to be a hypothesis at RevenueCat that this is a flaw to with a flaky test environment at Apple. How sure are we of this?

Unfortunately we get reports of Apple rejections regularly. This seems to be an issue with App Review not understanding the way their test environment works, and is unfortunately based on past reports from customers. The message from App Review about testing receipts in the correct environment is a template, and isn't related to the issue (RevenueCat always validates against the production validation endpoint first). 

Unfortunately, we've had cases of customers submitting the exact same build over a dozen times before being approved. I've also personally experienced this issue, where a subsequent build was approved without changes. It's extremely frustrating and there just isn't a lot of insight into the App Review process.

It looks like you also have a support ticket open, so I'm going to include some of the information about App Review here for others that might find this thread.

- If purchases are working correctly in sandbox and TestFlight, it's a good indicator that you have things set up correctly and this is an issue with the tester's environment.

- It's common in Apple's sandbox environment that a receipt isn't available on the device until a purchase is made, which could be causing this error to be returned. You might want to try requesting that the reviewer _makes_ a purchase before trying to _restore_ purchases.

- We've had some customers get their build approved by submitting a video of purchases working as expected in sandbox and communicating to the reviewer that this is a known issue in sandbox that isn't seen in production. In one extreme case, a customer was able to request a call with App Review and discuss the issue over the phone (this might have been paired with a rejection appeal).

I'd recommend continuing to submit your build and clarifying with the App Reviewer that purchases are being validated correctly and this is an issue with their test environment, as well as the fact the app has been available and working successfully in production for a period of time. Additionally, a video can't hurt - it might clarify that things are actually working as expected.

**Comment by djendacott** [comment]
Hi @codykerns ,

We finally got our iOS build approved. 

We ended up adding some code that if we strike a RCPurchasesErrorDomain response, instead of displaying the warning immediately, we would wait a few moments before trying again. 

I can't say if that contributed to our approval, or that we won't be back in the same position with our next update, but it at least worked for us this time.

**Comment by iTarek** [comment]
Today my app get rejected...
We found that your in-app purchase products exhibited one or more bugs when reviewed on iPad running iOS 15.6 on Wi-Fi.
After purchasing the In App Purchase, the App Store authenticated and confirmed, but the app failed to validate the receipt.

![Screenshot-0808-091954 png](https://user-images.githubusercontent.com/693715/183534384-66aeeffd-fa13-46e1-b67e-6b3a14bad8c2.jpeg)

You always blame the app review team, and ask them to use more than one device, and this was there reply...

Hello,
Thank you for your response. It appears your responses are copied from a separate entity that is handling your In App Purchases.

We attempted In App Purchases on two devices simultaneously, Before testing, we signed out of the App Store accounts on both devices, then signed in and verified different accounts on the two devices. We started by attempting a purchase (not a restore).

We observed the purchases being verified by the App Store in the test environment, followed be a failure of the app to validate the receipt. 


To be clear, other developer’s apps under review immediately before and after your app were able to successfully complete their In App Purchases. If RevenueCat is confirming purchases in a timely manner, there may be difficulty getting those validations back into your app. Also, if many RevenueCat customers are experiencing these issues, it may also suggest issues with their systems, or subsequent communication between their systems and yours. Thousands of other apps are not experiencing these issues, or are able to correct these issues after one rejection.

We look forward to reviewing your app once these issues have been addressed and the new build has been received and queued for review. Please be sure to resubmit any In App Purchase products along with the revised binary.


I am using the same code from your SwiftUI Example, and I am using the latest SDK, I really wonder when RevenueCat will give a solution else than blame the App Store review team.

Thank you and waiting for your reply.

**Comment by aboedo** [comment]
@KPUbhada we're happy to help, but in order to do that, could you answer some questions so we can figure out what's going on? 

First of all, is the screenshot coming directly from the rejection from the App Store Review team? I'm asking because the "receipt is missing" error should never happen _after_ a purchase has been made - the receipt is usually guaranteed to be on device once a purchase is made. 
We've seen that error show up when somebody attempts to restore purchases right after the app has been started, from a fresh install, on Sandbox, for example. In that specific case it would be expected since the receipt isn't present in the Sandbox environment until a user makes a purchase (in production, it's always present). 

Another question: you mentioned you're using the code from our SwiftUI example, and our latest SDK. Given that this conversation is in the React-Native SDK repo, could you clarify whether you're using the React-Native SDK or the iOS SDK, and which version number? That will help us a ton in debugging. 

In addition, if you're on React-Native, are you copy/pasting the code from SwiftUI and adding it as native iOS code, or are you porting the logic of purchases over? 

Also, and importantly: are you able to reproduce the issue the App Store Review ran into? If so, could you share the debug logs? They would go a long way into telling us what's going on.

**Comment by iTarek** [comment]
> First of all, is the screenshot coming directly from the rejection from the App Store Review team? 
Yes, and they have many other photos with another error
<img width="414" alt="Screenshot-0808-143809" src="https://user-images.githubusercontent.com/693715/183739487-1ddb06b2-8e25-40ba-ab41-befd92bf2149.png">

> Another question: you mentioned you're using the code from our SwiftUI example, and our latest SDK
Oh I am sorry I did not notice this is react native, I am using iOS SDK Native, and User your SwifUI Example as it's with just changes on the UI ad you see on the photos.

> Also, and importantly: are you able to reproduce the issue the App Store Review ran into? If so, could you share the debug logs? They would go a long way into telling us what's going on.

No for my tests, the app works good on simulator and test flight , I even upload video to App review team showing them that my app is working good, but I got the reply you saw.

Right now I uploaded another binary the only change in this binary was not show the error :) 
But because you always blame the Review Team, I think that I should share there reply with you so you can fix this. because it's really annoying, or at least show us the workaround that dev use when they got this problem.

Right Now I am thinking of restore before shwing the error, I am not a good developer, but what can I do...


```
                                    /// - Purchase a package
                                    Purchases.shared.purchase(package: package) { (transaction, info, error, userCancelled) in
                                        
                                        /// - If the user didn't cancel and there wasn't an error with the purchase, close the paywall
                                        if !userCancelled, error == nil {
                                            isPurchasing = false
                                            playerModel.pause()
                                        } else
                                        if let error = error {
                                            self.error = error as NSError
                                            if isSubscriptionActive == false {
                                                Purchases.shared.restorePurchases { info, error  in
                                                    if let subscription = info?.activeSubscriptions, subscription.isEmpty {
                                                        isPurchasing = false
                                                        self.displayError = true
                                                    }
                                                }
                                            }
                                        }
                                    }

```

I don't know even if this will work or not :) but doing anything better than nothing.

**Comment by aboedo** [comment]
@KPUbhada I'm sorry you're going through this. App Review is an infamously problematic process, and we've seen this kind of thing happen before quite a bit over the years. 
For what it's worth, thousands of other apps are using RevenueCat and aren't experiencing the issue, and given that you are able to make purchases locally and in TestFlight, it really seems like the issue is on StoreKit's side. 

One thought for something you could try, if you're running the latest iOS SDK (currently 4.10.0), is to make a build using a different version of StoreKit under the hood. 

We provide an option for it when configuring the SDK, here's some documentation on how to do that https://revenuecat.github.io/purchases-ios-docs/4.10.0/documentation/revenuecat/purchases/configure(with:)-6oipy

So if you're not passing in `usesStoreKit2IfAvailable` or you're passing in `false`, you could try making a build with `true`. 
If you're passing in `true`, you could make a build with `false`. 

Your app should behave the same way, so you don't need to update any code beyond the configuration. However, we've seen inconsistencies in the underlying StoreKit implementations on iOS where one works better sometimes and the other one works better some other times. 

The code you shared might also work as a workaround, assuming that the App Review team is correct in that the transaction is actually there but unfinished, but the restore could also fail if the purchase is failing, so I can't guarantee that it will make a difference either. Worth a shot, of course. 

> Right Now I am thinking of restore before showing the error, I am not a good developer, but what can I do...

That restore was a good idea and it makes you a good developer in my book 😺

**Comment by iTarek** [comment]
> That restore was a good idea and it makes you a good developer in my book 😺

You are a very kind man. I really like how you take time to reply even on the wrong thread.

But RevenueCat should address this problem and find a solution other than App Review is doing something wrong. I know that you already know about this problem

[App Store Rejections](https://docs.revenuecat.com/docs/app-store-rejections)

But look, how you handle a real problem like this

Other Tips
```
Reviewer provided "Next Steps"

Sometimes, the reviewer will provide you with "Next Steps" to resolve the rejection. These are usually not the most helpful in pinpointing any issues with purchases. One of the more common reasons is shown below:

When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment. The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code "Sandbox receipt used in production," you should validate against the test environment instead.
If you're using RevenueCat, sandbox and production purchases are automatically handled so even if the reviewer provides you with this reason, it's simply incorrect.
```

I guess if you give a solution like,  
```
If you're not passing in usesStoreKit2IfAvailable or you're passing in false, you could try making a build with true.
If you're passing in true, you could make a build with false.
```

would be better than say "it's simply incorrect" because in real life I can not tell the App Review team you are simply incorrect. And when I did they flagged  my app and now I am waiting for days "In Review"

AppReview team enjoy rejecting your app, and we do not want give them a reason to delay the approve for days, This is the real life.

Please work to find a solution for this I am sure you can find a work around this.

Thank you

**Comment by andrewchester1** [comment]
My app has been rejected for over a month because of broken functionality. The app reviewers can not see the revenue call paywall, but no errors are caught by sentry or anything. This integration works perfectly fine on a real device. Hate to see this issue has been around for a while, and sadly I will be looking for an alternative solution for in app payments.
