### ISSUE TITLE
checkTrialOrIntroductoryPriceEligibility returns status 0 since library update

### ISSUE THREAD

**Issue by KristineTrona** [RevenueCat/react-native-purchases#371]
- [x] I have updated Purchases SDK to the latest version
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**

Hello, I am calling `checkTrialOrIntroductoryPriceEligibility` in our app to determine if somebody is eligible for a free trial. Before library upgrade I was on version `4.3.0`, where calling this method worked without any problems, after the upgrade however I am always getting back:

```
status: 0,
description: "Status indeterminate."
```

I am testing on a real device with a new user and a new sandbox account user that has never had a subscription before. Reverting the package back to `4.3.0` fixes this issue, however it reopens [this problem](https://github.com/RevenueCat/react-native-purchases/issues/328), so we would really like to be able to upgrade. Any help is much appreciated! 

**Environment**
   Platform: iOS
   React Native version: 0.63.2
   React-native-purchases version: 4.6.0
   Xcode: 13.4
   Cocoapods: 1.11.3

**Comment by vegaro** [comment]
Thanks for opening @KristineTrona 

One quick question. Does the product actually have a trial configured? Does the purchase dialog show the trial being applied? Do you mind send us a screenshot of the purchase dialog?

Thanks!

**Comment by KristineTrona** [comment]
Thank you for your quick reply @vegaro. The product definitely has trial configured, because with exactly the same code, just package downgraded back to `4.3.0` I get:

```
status: 2
description: "Eligible for trial or introductory price."
```

What exactly do you mean by purchase dialog?

**Comment by KristineTrona** [comment]
@vegaro just checked and the Apple purchase dialog still says that the trial is being applied

**Comment by vegaro** [comment]
Hi @KristineTrona and @gramiro 

I've identified what's causing this. In order to fix https://github.com/RevenueCat/react-native-purchases/issues/328 we stopped refreshing the Apple receipt in the device when calling `checkTrialOrIntroductoryPriceEligibility`. That prevented the login popup from appearing when calling that method.

In sandbox, the receipt is always initially null, until a purchase or a restore is performed. So a side effect of [that fix](https://github.com/RevenueCat/react-native-purchases/issues/328) is that when initiating the app in sandbox the receipt is null and we will always return `"Status indeterminate"` for all products.

Again, this is common to happen in sandbox because in sandbox the receipt is empty until it's refreshed. In production the receipt should always be there and we will be able to determine the eligibility status. We decided to never refresh the receipt to prevent annoying login popups when calling `checkTrialOrIntroductoryPriceEligibility`. We decided to follow a silent fail + returning unknown approach since we think it's better than showing the login popup.

Can you try performing a `restore` in that brand-new sandbox user and see if calling `checkTrialOrIntroductoryPriceEligibility` after the restore returns the correct `"Eligible for trial or introductory price."`. I have just done this myself and started seeing the correct eligibility after performing a restore.

1. Start the app, eligibility is indeterminate due to receipt missing
2. Perform a restore which will not restore anything because there will be no purchases. The restore will refresh the receipt though.
3. Restart the app, eligibility will be the correct one, now that there's a receipt.

I hope that makes sense

**Comment by KristineTrona** [comment]
@vegaro thank you for looking into this, I can indeed confirm that after calling `restoreTransactions` and reopening the app the trial eligibility status is returned correctly.

However, how can I make sure that this does not happen to a real account in production? I've tested the app on a Testflight build, which doesn't use the development sandbox environment and still see the same issue happening. We display different information to our users depending on the trial eligibility, so it is easy to see that the status returned is still wrong.

1. I've tested a TF build before the library update and the same user is shown the free trial eligible content
2. I've tested a TF build after the library update and the same user is shown the free trial is not eligible content

**Comment by vegaro** [comment]
I should have mentioned that TestFlight behaves similar to sandbox in that sense. In production there should be a receipt and this should not happen. Sadly, the only way to test it is actually in production.

The reason we don’t refresh the receipt when calling `checkTrialOrIntroductoryPriceEligibility` is because this method is meant to be called “from the background” without user intervention. If we were to refresh the receipt it might prompt (it does not always prompt) the user to sign in, which would be confusing and add friction.

I should mention that we are preparing a new major version of the plugin that has some improvements and uses Apple StoreKit 2 when available. The StoreKit 2 implementation is much better when calculating the intro price and trial eligibility and doesn't require checking the receipt.

**Comment by KristineTrona** [comment]
@vegaro Ok, thanks for the explanation, I think we will wait for the new major version release and hopefully it works better then :)

**Comment by vegaro** [comment]
Sounds good! We are almost ready to release that new version.

I am going to close this issue if you don't mind to keep the repo tidy.
