### ISSUE TITLE
new version is failing in restoreTransactions operation

### ISSUE THREAD

**Issue by C3sarR0driguez** [RevenueCat/react-native-purchases#51]
Hi guys i am using last version 2.0.0, but when i am writing this code

 Purchases.restoreTransactions().then( (purchaserInfo, error) => {...
the native modules are failing restoring transactions.

![Screen Shot 2019-03-15 at 6 51 33 AM](https://user-images.githubusercontent.com/17457029/54432446-d3bc3b00-46ee-11e9-957d-b7c0142e6e00.png)

**Comment by vegaro** [comment]
Receipts are always present in production but when testing in sandbox they don't get created until a test in-app purchase has been made. That's why you are probably seeing that error. Take a look at [this](https://docs.revenuecat.com/discuss/5bcf290a826f1a002729c749) discussion. 

Can you confirm that making a purchase fixes the issue when restoring?
