### ISSUE TITLE
Purchases.getEntitlements() - Returning empty object on Android Simulator

### ISSUE THREAD

**Issue by spotelf13** [RevenueCat/react-native-purchases#52]
What are the common reasons to getting an empty entitlements object on Android but not on iOS? 

Installed package, linked dependencies, it is indeed "working" no exceptions. Just empty data not being returned.

**Comment by spotelf13** [comment]
Question: are there any manual docs to getting this setup w/ react native for android env? I noticed iOS is heavily documented but not android? Feels like I've missed a setup step for android maybe...

**Comment by vegaro** [comment]
If your Android Emulator has Play Services installed and you are logged in with an account, it should retrieve the entitlements without any needed configuration. You won't be able to make purchases on an emulator though, so I recommend you to test on a real device. Can you confirm you are using an emulator with Play Services and that you're logged in? You can call `Purchases.setDebugLogsEnabled(true);` if you are using `2.x.x` and get more descriptive logging that might help you debug the issue.

**Comment by spotelf13** [comment]
Hey @vegaro, we've got it running on a local device, signed into play store. We also have the in-app subscription product setup, however the getEntitlements is returning the monthly offering with a null value and not the product identifier. Any ideas?

**Comment by spotelf13** [comment]
Hey @vegaro don't worry it is all good and fixed. We just had to wait for play store to propagate the new in app purchasable.

**Comment by yastrebovb** [comment]
Having the same issue with my iOS app.

`Purchases.getEntitlements()` returns object with proper entitlement identification but the entitlement itself is empty. 
Tried playing around with configuration in the dashboard, no results though. I have the same code and logic in my other app and it's working absolutely fine. 

I believe it may be so because I'm developing a new app and IAP status is "Ready to submit" yet. Please let me know if this might be an issue.
