### ISSUE TITLE
null is not an object

### ISSUE THREAD

**Issue by EdwinDayot** [RevenueCat/react-native-purchases#63]
Hi,

I'm fairly new to React Native, so I probably don't understand how all of this should work.

I'm using Expo to hot reload on an external android device (and because it was the proposed version on the React Native website).

So I'm trying to build a subscription system on an app.

So i wrote in my App.js file the following:

```javascript
componentWillMount() {
        Purchases.setDebugLogsEnabled(true);
        Purchases.setup('***', null);
    }
```

But the app crashes with the following lines:
```
Uncaught Error: TypeError: null is not an object (evaluating 's.setDebugLogsEnabled')

This error is located at:
  in v
  in v
  in RCTView
  in RCTView
  in c
```

(These lines only appear on the device, not in the Metro Bundler nor in the terminal)

**Comment by vegaro** [comment]
Hi @EdwinDayot!

Take into account that we are not compatible with Expo. In order to use the latest version of our SDK you have to eject the app to React Native. If you eject to ExpoKit you have to use version `2.0.1` since it uses an older version of React Native compatible with ExpoKit. 

In your package.json:
`"react-native-purchases": "2.0.1"`

Cheers!

**Comment by EdwinDayot** [comment]
Thanks :)
