### ISSUE TITLE
Android userInfoMap rejection

### ISSUE THREAD

**Issue by josaric** [RevenueCat/react-native-purchases#67]
Issue is related with:
https://github.com/RevenueCat/react-native-purchases/issues/58

On every npm install, I need to go and edit RNPurchaseModule.java

Please add Throwable function:
function line: 441
`private static void reject(Promise promise, PurchasesError error)`

this is the old code
`promise.reject(error.getCode().ordinal() + "", error.getMessage(), userInfoMap);`

this is how to fix the issue:

`promise.reject(error.getCode().ordinal() + "", error.getMessage(), (Throwable) userInfoMap);`

**Comment by vegaro** [comment]
Thanks for reporting. We require React Native 0.58 to provide more meaningful errors. That method required a Throwable before 0.58 and `userInfoMap` is a map, and that's why the IDE is asking to pass a Throwable. If you are using ExpoKit, you should use the version [2.0.1](https://github.com/RevenueCat/react-native-purchases/releases/tag/expo-patch) of this SDK.

**Comment by josaric** [comment]
@vegaro I'm using an expokit but while trying to compile run dev env on mobile phone, android studio return this error on app build:

> error: incompatible types: WritableMap cannot be converted to Throwable

**Comment by vegaro** [comment]
@josaric What version of the Purchases SDK are you using?
